export enum rendererSendEvents {
  RUN_OCR = 'RUNOCR',
  RUN_PDF_TO_IMAGES = 'RUN_PDF_TO_IMAGES',
}

export enum rendererRecieveEvents {
  OCR_DONE = 'OCRDONE:RENDERER',
  UPDATE_LOGGERS = 'UPDATELOGGERS',
  ONE_PAGE_CONVERTED = 'ONEPAGECONVERTED',
  ONE_IMAGE_CONVERTED = 'ONE_IMAGE_CONVERTED',
  IMAGE_CONVERT_DONE = 'IMAGE_CONVERT_DONE',
}

export enum mainEvents {
  OCR_DONE = 'OCRDONE:MAIN',
  ERROR_MAIN = 'ERROR:MAIN',
}
